-- 여기는 USER1 화면입니다.
CREATE TABLE tbl_member (
        M_USERID	VARCHAR2(50)		PRIMARY KEY,
        M_PASSWORD	VARCHAR2(125)	NOT NULL,	
        M_NAME	nVARCHAR2(30)	NOT NULL,	
        M_TEL	VARCHAR2(20),		
        M_ADDRESS	nVARCHAR2(255),		
        M_ROLE	VARCHAR2(20)		
);

SELECT * FROM tbl_member;